### ISSUE TITLE
Anyone to Maintain repo as per Hacktoberrfest Rules!

### ISSUE THREAD

**Issue by ossamamehmood** [ossamamehmood/Hacktoberfest#5822]
Need someone to rebuild my repository within the rule mentioned by Hacktoberfest!

- You can reconsider this REPO to Hacktoberfest to fix up (Excluded Repo Issue)

- Further, Approve the PRs as the maintainer's rule described in Hacktoberfest

Note: The repo is excluded from Hacktoberfest f you can control the spam and apply the rule of conduct as Hacktoberfest we can request them to reconsider our repo and then we can maintain the quality of the contribution

Thank You So Much, Would love to have someone as a CO-Maintainer!

**Comment by Vivekp3005** [comment]
Hello, can you explain in brief what did you expect to change in your repo?

**Comment by ossamamehmood** [comment]
We need to make the repo as per the HACKTOBERFEST guidelines.

- They have mentioned the maintainers guidelines we just need to follow them

**Comment by sharma62** [comment]
# Protocol list  For Contributor

> ## Note Follow these steps. 

1.  Registration: You need to register for Hacktoberfest on the official website to be eligible for participation.

2. Pull Requests: To qualify for Hacktoberfest, you must submit a minimum of four valid pull requests (PRs) during the month of October. These PRs must be made to public repositories on GitHub.

3. Quality over Quantity: While you're encouraged to make multiple contributions, the emphasis should be on quality rather than quantity. Avoid spammy or trivial PRs.

4. Projects: Contributions can be made to any public GitHub repository. You're encouraged to contribute to open-source projects that interest you.

5. Issues: Look for issues labeled as "Hacktoberfest" or "good first issue" in the repositories you want to contribute to. These issues are often beginner-friendly.

6. Code of Conduct: Always follow the code of conduct and contribution guidelines of the projects you contribute to. Be respectful and follow the maintainers' instructions.

7. Ownership: Make meaningful contributions to projects. Ensure your PRs add value to the project and are accepted by maintainers.

8. Diversity: Encourage diversity in open-source. Hacktoberfest values contributions from individuals of all backgrounds and experience levels.

9. No Duplicate Contributions: Each PR should provide a meaningful change. Avoid submitting duplicate or minor changes to multiple repositories.

10. Spam Prevention: PRs that are considered spammy, such as those with irrelevant content or excessive changes, may not be counted towards Hacktoberfest.

11. Valid PRs: PRs must be approved and merged by the project maintainers or have a "valid" label on them to be counted toward Hacktoberfest.

12. Review Contributions: Review and provide constructive feedback on others' PRs if you have the expertise. Encourage a collaborative atmosphere.

13 . Timeline: PRs made outside of October may not be counted, so ensure your contributions are within the specified timeframe.

**Comment by ossamamehmood** [comment]
@sharma62 I'm aware of these points looking for Co-Maintainer to manage the REPO with me!

**Comment by sharma62** [comment]
@ossamamehmood so try me as **Co-Maintainer** with you?

**Comment by ossamamehmood** [comment]
Why not? If you are interested reach out me in Linkedin anywhere to discuss upon

**Comment by sharma62** [comment]
**fine, I do. You check out.**

**Comment by axitchandora** [comment]
I am interested.

**Comment by ossamamehmood** [comment]
@axitchandora You can contact me too I'm up for multiple guys to work with me on that!

**Comment by mohitsaini07** [comment]
Hi @ossamamehmood, I would like to work on this

**Comment by shaman-004** [comment]
can i , i am also interested @ossamamehmood

**Comment by ossamamehmood** [comment]
@shaman-004 & @mohitsaini07 Yes sure contact me on LinkedIn. I'll  schedule a meeting upon and we'll discuss that!

**Comment by dharmraj617** [comment]
Let me on board too @ossamamehmood . I have learned advanced concepts in Python and DSA. also, I am quite experienced in GitHub.  I do have a lot in my arsenal such as Flutter development and Java. I am currently learning ML too.

**Comment by ossamamehmood** [comment]
Great ! Can you get to connect me on LinkedIn we'll set up a chat group add everyone and schedule the meeting!

**Comment by Chifez** [comment]
do you have any prerequisite when choosing a co-maintainer?

**Comment by kharshita590** [comment]
hey I am also interested

**Comment by Vishal-1004** [comment]
hii @ossamamehmood and @sharma62 sorry to bring this over here,
but the thing is i too wish to contribute to this repo but not in the same way of giving pic and adding it in some folder and all.....

So I have got a feature to add to this repo and that is adding scroll to top button to the Readme.md file because the readme file of your's is big so if we provide this feature anyway can just click on that button which is available in readme.md file and will get scrolled to the top.

So can i please raise an issue for this and work on it.

**Comment by ossamamehmood** [comment]
Joined the WhatsApp chat group so we can planned about maintaining a proper hacktoberfest repo: https://chat.whatsapp.com/Cnep6IFFKsz90X5CpB8tt5

**Comment by snehalshah8429** [comment]
Pleasant Greetings
is the issue still open?
I'm willing to contribute on this issue.

**Comment by swarajmhatre** [comment]
Hi! I am willing to work on this repo. I am quite experienced with open-source and version control. Please add me up in this issue.

**Comment by nevo-david** [comment]
This repo is excluded also in HackSquad, contribution will result in an automated ban.

**Comment by mayank9369** [comment]
> Need someone to rebuild my repository within the rule mentioned by Hacktoberfest!
> 
> * You can reconsider this REPO to Hacktoberfest to fix up (Excluded Repo Issue)
> * Further, Approve the PRs as the maintainer's rule described in Hacktoberfest
> 
> Note: The repo is excluded from Hacktoberfest f you can control the spam and apply the rule of conduct as Hacktoberfest we can request them to reconsider our repo and then we can maintain the quality of the contribution
> 
> Thank You So Much, Would love to have someone as a CO-Maintainer!

**Comment by mayank9369** [comment]
May I assist you? I am also interested.

**Comment by Sanchitbajaj02** [comment]
Hi, @ossamamehmood 
I want to know whether this issue is resolved or not. If not, I can assist you with that so please assign this issue to me as well

**Comment by ossamamehmood** [comment]
We have created a new repository : 
https://github.com/ossamamehmood/Hacktoberfest2023

Note: This current repo was excluded due to high volume spam and low-quality contribution. So, we set up a new repo that follows #hacktoberfest guidelines.

Additionally, we acknowledge fair and quality contributions. You must follow Hacktooberfest contribution guidelines to approve your Pull Request!

Special thanks to our maintainer's team who are always trying to improve the quality of Hacktoberfest events from now onwards.
